### ISSUE TITLE
Can't get attribute 'Word2Man' 

### ISSUE THREAD

**Issue by djinn-anthrope** [bollu/alok-bollu#6]
Running on branch alok-evaluation, as branch master does not seem to have a models directory. 

Command: `python3 run.py eval models/working-word2vec-baseline-b0c2872c `

Output:
	
	setting up device...
    device: cuda:1
	====time: 0:00:00.616033
	loading model from: models/working-word2vec-baseline-b0c2872c...
	Traceback (most recent call last):
  	File "run.py", line 758, in <module>
   	 PARAMS = torch.load(PARSED.loadpath, map_location=DEVICE)
 	 File "/home/alokdebnath5/.local/lib/python3.5/site-packages/torch/serialization.py", line 367, in load
    	return _load(f, map_location, pickle_module)
  	File "/home/alokdebnath5/.local/lib/python3.5/site-packages/torch/serialization.py", line 538, in _load
    	result = unpickler.load()
	AttributeError: Can't get attribute 'Word2Man' on <module '__main__' from 'run.py'>
`
Need help in figuring out why this is happening?

**Comment by djinn-anthrope** [comment]
@bollu Tagging you for help
